"""Data models for GitHub analysis."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class GithubProject:
    """A repository analysed from a GitHub profile.

    Attributes:
        repo_name: Full repository name (e.g. ``user/repo``).
        description: Repository description from GitHub.
        url: HTTPS URL to the repository.
        languages: Programming languages detected by GitHub, e.g.
            ``{"Python": 45000, "JavaScript": 12000}`` (bytes per language).
        topics: Repository topic tags.
        stars: Star count.
        readme: Full README content (or truncated).
        detected_skills: Skills/technologies inferred by
            :class:`RepoAnalyzer` from the repo's contents.
        summary: Human-readable summary generated by :class:`RepoAnalyzer`.
    """

    repo_name: str = ""
    description: str = ""
    url: str = ""
    languages: dict[str, int] = field(default_factory=dict)
    topics: list[str] = field(default_factory=list)
    stars: int = 0
    readme: str = ""
    detected_skills: list[str] = field(default_factory=list)
    summary: str = ""


@dataclass
class GithubProfile:
    """A GitHub user's public profile with analysed projects.

    Attributes:
        username: GitHub username.
        projects: List of analysed :class:`GithubProject` entries.
    """

    username: str = ""
    projects: list[GithubProject] = field(default_factory=list)
