"""Data models for portfolio analysis."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PortfolioProject:
    """A project extracted from a portfolio website.

    Attributes:
        name: Project title.
        description: Short description or excerpt.
        technologies: Technologies, frameworks, or tools detected for
            this project.
        project_url: Direct link to the project page or demo.
        github_url: Link to the source repository (if present).
        summary: Human-readable summary generated by
            :class:`PortfolioAnalyzer`.
    """

    name: str = ""
    description: str = ""
    technologies: list[str] = field(default_factory=list)
    project_url: str = ""
    github_url: str = ""
    keywords: list[str] = field(default_factory=list)
    summary: str = ""


@dataclass
class PortfolioProfile:
    """A parsed portfolio website with its projects.

    Attributes:
        portfolio_url: The URL of the portfolio website.
        projects: List of extracted :class:`PortfolioProject` entries.
    """

    portfolio_url: str = ""
    projects: list[PortfolioProject] = field(default_factory=list)
